from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 323)
        MainWindow.setMinimumSize(QtCore.QSize(0, 70))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(80, 70, 721, 61))
        self.gridLayoutWidget.setAutoFillBackground(True)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.qwe = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.qwe.setContentsMargins(0, 0, 0, 0)
        self.qwe.setObjectName("qwe")
        
        self.btn_w = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_w.setAutoFillBackground(True)
        self.btn_w.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_w.setObjectName("btn_w")
        self.qwe.addWidget(self.btn_w, 0, 1, 1, 1)
        
        self.btn_u = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_u.setAutoFillBackground(True)
        self.btn_u.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_u.setObjectName("btn_u")
        self.qwe.addWidget(self.btn_u, 0, 6, 1, 1)
        
        self.btn_q = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_q.setMinimumSize(QtCore.QSize(54, 40))
        self.btn_q.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_q.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_q.setAutoFillBackground(True)
        self.btn_q.setScaledContents(False)
        self.btn_q.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_q.setObjectName("btn_q")
        self.qwe.addWidget(self.btn_q, 0, 0, 1, 1)
        
        self.btn_o = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_o.setAutoFillBackground(True)
        self.btn_o.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_o.setObjectName("btn_o")
        self.qwe.addWidget(self.btn_o, 0, 8, 1, 1)
        
        self.btn_op_scq_br = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_op_scq_br.setAutoFillBackground(True)
        self.btn_op_scq_br.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_op_scq_br.setObjectName("btn_op_scq_br")
        self.qwe.addWidget(self.btn_op_scq_br, 0, 10, 1, 1)
        
        self.btn_p = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_p.setAutoFillBackground(True)
        self.btn_p.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_p.setObjectName("btn_p")
        self.qwe.addWidget(self.btn_p, 0, 9, 1, 1)
        
        self.btn_i = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_i.setAutoFillBackground(True)
        self.btn_i.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_i.setObjectName("btn_i")
        self.qwe.addWidget(self.btn_i, 0, 7, 1, 1)
        
        self.btn_y = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_y.setAutoFillBackground(True)
        self.btn_y.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_y.setObjectName("btn_y")
        self.qwe.addWidget(self.btn_y, 0, 5, 1, 1)
        
        self.btn_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_t.setAutoFillBackground(True)
        self.btn_t.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_t.setObjectName("btn_t")
        self.qwe.addWidget(self.btn_t, 0, 4, 1, 1)
       
        self.scr_p = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_p.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_p.setAutoFillBackground(True)
        self.scr_p.setScaledContents(False)
        self.scr_p.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_p.setObjectName("scr_p")
        self.qwe.addWidget(self.scr_p, 1, 9, 1, 1)
        
        self.scr_i = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_i.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_i.setAutoFillBackground(True)
        self.scr_i.setScaledContents(False)
        self.scr_i.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_i.setObjectName("scr_i")
        self.qwe.addWidget(self.scr_i, 1, 7, 1, 1)
        
        self.btn_cl_sqr_br = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_cl_sqr_br.setAutoFillBackground(True)
        self.btn_cl_sqr_br.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_cl_sqr_br.setObjectName("btn_cl_sqr_br")
        self.qwe.addWidget(self.btn_cl_sqr_br, 0, 11, 1, 1)
        
        self.scr_op_scq_b = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_op_scq_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_op_scq_b.setAutoFillBackground(True)
        self.scr_op_scq_b.setScaledContents(False)
        self.scr_op_scq_b.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_op_scq_b.setObjectName("scr_op_scq_b")
        self.qwe.addWidget(self.scr_op_scq_b, 1, 10, 1, 1)
        
        self.scr_w = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_w.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_w.setAutoFillBackground(True)
        self.scr_w.setScaledContents(False)
        self.scr_w.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_w.setObjectName("scr_w")
        self.qwe.addWidget(self.scr_w, 1, 1, 1, 1)
        
        self.scr_cl_sqr_br = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_cl_sqr_br.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_cl_sqr_br.setAutoFillBackground(True)
        self.scr_cl_sqr_br.setScaledContents(False)
        self.scr_cl_sqr_br.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_cl_sqr_br.setObjectName("scr_cl_sqr_br")
        self.qwe.addWidget(self.scr_cl_sqr_br, 1, 11, 1, 1)
        
        self.scr_t = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_t.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_t.setAutoFillBackground(True)
        self.scr_t.setScaledContents(False)
        self.scr_t.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_t.setObjectName("scr_t")
        self.qwe.addWidget(self.scr_t, 1, 4, 1, 1)
        
        self.scr_y = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_y.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_y.setAutoFillBackground(True)
        self.scr_y.setScaledContents(False)
        self.scr_y.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_y.setObjectName("scr_y")
        self.qwe.addWidget(self.scr_y, 1, 5, 1, 1)
        
        self.scr_u = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_u.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_u.setAutoFillBackground(True)
        self.scr_u.setScaledContents(False)
        self.scr_u.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_u.setObjectName("scr_u")
        self.qwe.addWidget(self.scr_u, 1, 6, 1, 1)
        
        self.scr_o = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_o.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_o.setAutoFillBackground(True)
        self.scr_o.setScaledContents(False)
        self.scr_o.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_o.setObjectName("scr_o")
        self.qwe.addWidget(self.scr_o, 1, 8, 1, 1)
        
        self.scr_e = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_e.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_e.setAutoFillBackground(True)
        self.scr_e.setScaledContents(False)
        self.scr_e.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_e.setObjectName("scr_e")
        self.qwe.addWidget(self.scr_e, 1, 2, 1, 1)
        
        self.scr_r = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_r.setAutoFillBackground(True)
        self.scr_r.setScaledContents(False)
        self.scr_r.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_r.setObjectName("scr_r")
        self.qwe.addWidget(self.scr_r, 1, 3, 1, 1)
        
        self.btn_r = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_r.setAutoFillBackground(True)
        self.btn_r.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_r.setObjectName("btn_r")
        self.qwe.addWidget(self.btn_r, 0, 3, 1, 1)
        
        self.btn_e = QtWidgets.QLabel(self.gridLayoutWidget)
        self.btn_e.setAutoFillBackground(True)
        self.btn_e.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_e.setObjectName("btn_e")
        self.qwe.addWidget(self.btn_e, 0, 2, 1, 1)
        
        self.scr_q = QtWidgets.QLabel(self.gridLayoutWidget)
        self.scr_q.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_q.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_q.setAutoFillBackground(True)
        self.scr_q.setScaledContents(False)
        self.scr_q.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_q.setObjectName("scr_q")
        self.qwe.addWidget(self.scr_q, 1, 0, 1, 1)
        
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(90, 130, 661, 61))
        self.gridLayoutWidget_2.setAutoFillBackground(True)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        
        self.asd = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.asd.setContentsMargins(0, 0, 0, 0)
        self.asd.setObjectName("asd")
        
        self.btn_g = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_g.setAutoFillBackground(True)
        self.btn_g.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_g.setObjectName("btn_g")
        self.asd.addWidget(self.btn_g, 0, 4, 1, 1)
        
        self.btn_d = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_d.setAutoFillBackground(True)
        self.btn_d.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_d.setObjectName("btn_d")
        self.asd.addWidget(self.btn_d, 0, 2, 1, 1)
        
        self.btn_f = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_f.setAutoFillBackground(True)
        self.btn_f.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_f.setObjectName("btn_f")
        self.asd.addWidget(self.btn_f, 0, 3, 1, 1)
        
        self.scr_a = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_a.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_a.setAutoFillBackground(True)
        self.scr_a.setScaledContents(False)
        self.scr_a.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_a.setObjectName("scr_a")
        self.asd.addWidget(self.scr_a, 1, 0, 1, 1)
        
        self.btn_a = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_a.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_a.setAutoFillBackground(True)
        self.btn_a.setScaledContents(False)
        self.btn_a.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_a.setObjectName("btn_a")
        self.asd.addWidget(self.btn_a, 0, 0, 1, 1)
        
        self.btn_semicolon = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_semicolon.setAutoFillBackground(True)
        self.btn_semicolon.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_semicolon.setObjectName("btn_semicolon")
        self.asd.addWidget(self.btn_semicolon, 0, 9, 1, 1)
        
        self.btn_k = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_k.setAutoFillBackground(True)
        self.btn_k.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_k.setObjectName("btn_k")
        self.asd.addWidget(self.btn_k, 0, 7, 1, 1)
        
        self.btn_h = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_h.setAutoFillBackground(True)
        self.btn_h.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_h.setObjectName("btn_h")
        self.asd.addWidget(self.btn_h, 0, 5, 1, 1)
        
        self.btn_s = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_s.setAutoFillBackground(True)
        self.btn_s.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_s.setObjectName("btn_s")
        self.asd.addWidget(self.btn_s, 0, 1, 1, 1)
        
        self.btn_j = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_j.setAutoFillBackground(True)
        self.btn_j.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_j.setObjectName("btn_j")
        self.asd.addWidget(self.btn_j, 0, 6, 1, 1)
        
        self.btn_l = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_l.setAutoFillBackground(True)
        self.btn_l.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_l.setObjectName("btn_l")
        self.asd.addWidget(self.btn_l, 0, 8, 1, 1)
        
        self.btn_apstf = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.btn_apstf.setAutoFillBackground(True)
        self.btn_apstf.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_apstf.setObjectName("btn_apstf")
        self.asd.addWidget(self.btn_apstf, 0, 10, 1, 1)
        
        self.scr_s = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_s.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_s.setAutoFillBackground(True)
        self.scr_s.setScaledContents(False)
        self.scr_s.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_s.setObjectName("scr_s")
        self.asd.addWidget(self.scr_s, 1, 1, 1, 1)
        
        self.scr_d = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_d.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_d.setAutoFillBackground(True)
        self.scr_d.setScaledContents(False)
        self.scr_d.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_d.setObjectName("scr_d")
        self.asd.addWidget(self.scr_d, 1, 2, 1, 1)
        
        self.scr_f = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_f.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_f.setAutoFillBackground(True)
        self.scr_f.setScaledContents(False)
        self.scr_f.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_f.setObjectName("scr_f")
        self.asd.addWidget(self.scr_f, 1, 3, 1, 1)
        
        self.scr_g = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_g.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_g.setAutoFillBackground(True)
        self.scr_g.setScaledContents(False)
        self.scr_g.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_g.setObjectName("scr_g")
        self.asd.addWidget(self.scr_g, 1, 4, 1, 1)
        
        self.scr_h = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_h.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_h.setAutoFillBackground(True)
        self.scr_h.setScaledContents(False)
        self.scr_h.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_h.setObjectName("scr_h")
        self.asd.addWidget(self.scr_h, 1, 5, 1, 1)
        
        self.scr_j = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_j.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_j.setAutoFillBackground(True)
        self.scr_j.setScaledContents(False)
        self.scr_j.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_j.setObjectName("scr_j")
        self.asd.addWidget(self.scr_j, 1, 6, 1, 1)
        
        self.scr_k = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_k.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_k.setAutoFillBackground(True)
        self.scr_k.setScaledContents(False)
        self.scr_k.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_k.setObjectName("scr_k")
        self.asd.addWidget(self.scr_k, 1, 7, 1, 1)
        
        self.scr_l = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_l.setAutoFillBackground(True)
        self.scr_l.setScaledContents(False)
        self.scr_l.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_l.setObjectName("scr_l")
        self.asd.addWidget(self.scr_l, 1, 8, 1, 1)
        
        self.scr_semicolon = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_semicolon.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_semicolon.setAutoFillBackground(True)
        self.scr_semicolon.setScaledContents(False)
        self.scr_semicolon.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_semicolon.setObjectName("scr_semicolon")
        self.asd.addWidget(self.scr_semicolon, 1, 9, 1, 1)
        
        self.scr_apstrf = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.scr_apstrf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_apstrf.setAutoFillBackground(True)
        self.scr_apstrf.setScaledContents(False)
        self.scr_apstrf.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_apstrf.setObjectName("scr_apstrf")
        self.asd.addWidget(self.scr_apstrf, 1, 10, 1, 1)
        
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(120, 190, 601, 61))
        self.gridLayoutWidget_3.setAutoFillBackground(True)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.zxc = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.zxc.setContentsMargins(0, 0, 0, 0)
        self.zxc.setObjectName("zxc")
        self.btn_z = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_z.setAutoFillBackground(True)
        self.btn_z.setScaledContents(False)
        self.btn_z.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_z.setObjectName("btn_z")
        self.zxc.addWidget(self.btn_z, 0, 0, 1, 1)
        self.btn_m = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_m.setAutoFillBackground(True)
        self.btn_m.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_m.setObjectName("btn_m")
        self.zxc.addWidget(self.btn_m, 0, 6, 1, 1)
        self.btn_dot = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_dot.setAutoFillBackground(True)
        self.btn_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_dot.setObjectName("btn_dot")
        self.zxc.addWidget(self.btn_dot, 0, 8, 1, 1)
        self.btn_b = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_b.setAutoFillBackground(True)
        self.btn_b.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_b.setObjectName("btn_b")
        self.zxc.addWidget(self.btn_b, 0, 4, 1, 1)
        self.btn_c = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_c.setAutoFillBackground(True)
        self.btn_c.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_c.setObjectName("btn_c")
        self.zxc.addWidget(self.btn_c, 0, 2, 1, 1)
        self.btn_comma = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_comma.setAutoFillBackground(True)
        self.btn_comma.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_comma.setObjectName("btn_comma")
        self.zxc.addWidget(self.btn_comma, 0, 7, 1, 1)
        self.btn_f_slash = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_f_slash.setAutoFillBackground(True)
        self.btn_f_slash.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_f_slash.setObjectName("btn_f_slash")
        self.zxc.addWidget(self.btn_f_slash, 0, 9, 1, 1)
        self.btn_n = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_n.setAutoFillBackground(True)
        self.btn_n.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_n.setObjectName("btn_n")
        self.zxc.addWidget(self.btn_n, 0, 5, 1, 1)
        self.btn_v = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_v.setAutoFillBackground(True)
        self.btn_v.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_v.setObjectName("btn_v")
        self.zxc.addWidget(self.btn_v, 0, 3, 1, 1)
        self.btn_x = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.btn_x.setAutoFillBackground(True)
        self.btn_x.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_x.setObjectName("btn_x")
        self.zxc.addWidget(self.btn_x, 0, 1, 1, 1)
        self.scr_z = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_z.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_z.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_z.setAutoFillBackground(True)
        self.scr_z.setScaledContents(False)
        self.scr_z.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_z.setObjectName("scr_z")
        self.zxc.addWidget(self.scr_z, 1, 0, 1, 1)
        self.scr_x = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_x.setAutoFillBackground(True)
        self.scr_x.setScaledContents(False)
        self.scr_x.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_x.setObjectName("scr_x")
        self.zxc.addWidget(self.scr_x, 1, 1, 1, 1)
        self.scr_c = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_c.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_c.setAutoFillBackground(True)
        self.scr_c.setScaledContents(False)
        self.scr_c.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_c.setObjectName("scr_c")
        self.zxc.addWidget(self.scr_c, 1, 2, 1, 1)
        self.scr_v = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_v.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_v.setAutoFillBackground(True)
        self.scr_v.setScaledContents(False)
        self.scr_v.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_v.setObjectName("scr_v")
        self.zxc.addWidget(self.scr_v, 1, 3, 1, 1)
        self.scr_b = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_b.setAutoFillBackground(True)
        self.scr_b.setScaledContents(False)
        self.scr_b.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_b.setObjectName("scr_b")
        self.zxc.addWidget(self.scr_b, 1, 4, 1, 1)
        self.scr_n = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_n.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n.setAutoFillBackground(True)
        self.scr_n.setScaledContents(False)
        self.scr_n.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n.setObjectName("scr_n")
        self.zxc.addWidget(self.scr_n, 1, 5, 1, 1)
        self.scr_m = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_m.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_m.setAutoFillBackground(True)
        self.scr_m.setScaledContents(False)
        self.scr_m.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_m.setObjectName("scr_m")
        self.zxc.addWidget(self.scr_m, 1, 6, 1, 1)
        self.scr_comma = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_comma.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_comma.setAutoFillBackground(True)
        self.scr_comma.setScaledContents(False)
        self.scr_comma.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_comma.setObjectName("scr_comma")
        self.zxc.addWidget(self.scr_comma, 1, 7, 1, 1)
        self.scr_dot = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_dot.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_dot.setAutoFillBackground(True)
        self.scr_dot.setScaledContents(False)
        self.scr_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_dot.setObjectName("scr_dot")
        self.zxc.addWidget(self.scr_dot, 1, 8, 1, 1)
        self.scr_f_slash = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.scr_f_slash.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_f_slash.setAutoFillBackground(True)
        self.scr_f_slash.setScaledContents(False)
        self.scr_f_slash.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_f_slash.setObjectName("scr_f_slash")
        self.zxc.addWidget(self.scr_f_slash, 1, 9, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 70, 71, 61))
        self.gridLayoutWidget_4.setAutoFillBackground(True)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.Tab = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.Tab.setContentsMargins(0, 0, 0, 0)
        self.Tab.setObjectName("Tab")
        self.btn_tab = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.btn_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_tab.setAutoFillBackground(True)
        self.btn_tab.setScaledContents(False)
        self.btn_tab.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_tab.setObjectName("btn_tab")
        self.Tab.addWidget(self.btn_tab, 0, 0, 1, 1)
        self.scr_tab = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.scr_tab.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_tab.setAutoFillBackground(True)
        self.scr_tab.setScaledContents(False)
        self.scr_tab.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_tab.setObjectName("scr_tab")
        self.Tab.addWidget(self.scr_tab, 1, 0, 1, 1)
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(10, 130, 81, 61))
        self.gridLayoutWidget_5.setAutoFillBackground(True)
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.CapsL = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.CapsL.setContentsMargins(0, 0, 0, 0)
        self.CapsL.setObjectName("CapsL")
        self.btn_capslock = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.btn_capslock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_capslock.setAutoFillBackground(True)
        self.btn_capslock.setScaledContents(False)
        self.btn_capslock.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_capslock.setObjectName("btn_capslock")
        self.CapsL.addWidget(self.btn_capslock, 0, 0, 1, 1)
        self.scr_capslock = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.scr_capslock.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_capslock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_capslock.setAutoFillBackground(True)
        self.scr_capslock.setScaledContents(False)
        self.scr_capslock.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_capslock.setObjectName("scr_capslock")
        self.CapsL.addWidget(self.scr_capslock, 1, 0, 1, 1)
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 190, 111, 61))
        self.gridLayoutWidget_6.setAutoFillBackground(True)
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.Shift = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.Shift.setContentsMargins(0, 0, 0, 0)
        self.Shift.setObjectName("Shift")
        self.btn_shift = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.btn_shift.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_shift.setAutoFillBackground(True)
        self.btn_shift.setScaledContents(False)
        self.btn_shift.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_shift.setObjectName("btn_shift")
        self.Shift.addWidget(self.btn_shift, 0, 0, 1, 1)
        self.scr_shift = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.scr_shift.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_shift.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_shift.setAutoFillBackground(True)
        self.scr_shift.setScaledContents(False)
        self.scr_shift.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_shift.setObjectName("scr_shift")
        self.Shift.addWidget(self.scr_shift, 1, 0, 1, 1)
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(60, 10, 711, 61))
        self.gridLayoutWidget_7.setAutoFillBackground(True)
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.qwe_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.qwe_2.setContentsMargins(0, 0, 0, 0)
        self.qwe_2.setObjectName("qwe_2")
        self.btn_minus = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_minus.setAutoFillBackground(True)
        self.btn_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_minus.setObjectName("btn_minus")
        self.qwe_2.addWidget(self.btn_minus, 0, 10, 1, 1)
        self.btn_9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_9.setAutoFillBackground(True)
        self.btn_9.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_9.setObjectName("btn_9")
        self.qwe_2.addWidget(self.btn_9, 0, 8, 1, 1)
        self.btn_0 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_0.setAutoFillBackground(True)
        self.btn_0.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_0.setObjectName("btn_0")
        self.qwe_2.addWidget(self.btn_0, 0, 9, 1, 1)
        self.btn_8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_8.setAutoFillBackground(True)
        self.btn_8.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_8.setObjectName("btn_8")
        self.qwe_2.addWidget(self.btn_8, 0, 7, 1, 1)
        self.btn_equal = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_equal.setAutoFillBackground(True)
        self.btn_equal.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_equal.setObjectName("btn_equal")
        self.qwe_2.addWidget(self.btn_equal, 0, 11, 1, 1)
        self.btn_6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_6.setAutoFillBackground(True)
        self.btn_6.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_6.setObjectName("btn_6")
        self.qwe_2.addWidget(self.btn_6, 0, 5, 1, 1)
        self.btn_5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_5.setAutoFillBackground(True)
        self.btn_5.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_5.setObjectName("btn_5")
        self.qwe_2.addWidget(self.btn_5, 0, 4, 1, 1)
        self.btn_4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_4.setAutoFillBackground(True)
        self.btn_4.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_4.setObjectName("btn_4")
        self.qwe_2.addWidget(self.btn_4, 0, 3, 1, 1)
        self.btn_3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_3.setAutoFillBackground(True)
        self.btn_3.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_3.setObjectName("btn_3")
        self.qwe_2.addWidget(self.btn_3, 0, 2, 1, 1)
        self.btn_2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_2.setAutoFillBackground(True)
        self.btn_2.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_2.setObjectName("btn_2")
        self.qwe_2.addWidget(self.btn_2, 0, 1, 1, 1)
        self.btn_1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_1.setMinimumSize(QtCore.QSize(54, 0))
        self.btn_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_1.setAutoFillBackground(True)
        self.btn_1.setScaledContents(False)
        self.btn_1.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_1.setObjectName("btn_1")
        self.qwe_2.addWidget(self.btn_1, 0, 0, 1, 1)
        self.btn_7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.btn_7.setAutoFillBackground(True)
        self.btn_7.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_7.setObjectName("btn_7")
        self.qwe_2.addWidget(self.btn_7, 0, 6, 1, 1)
        self.scr_ecuals = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_ecuals.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_ecuals.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_ecuals.setAutoFillBackground(True)
        self.scr_ecuals.setScaledContents(False)
        self.scr_ecuals.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_ecuals.setObjectName("scr_ecuals")
        self.qwe_2.addWidget(self.scr_ecuals, 1, 11, 1, 1)
        self.scr_minus = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_minus.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_minus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_minus.setAutoFillBackground(True)
        self.scr_minus.setScaledContents(False)
        self.scr_minus.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_minus.setObjectName("scr_minus")
        self.qwe_2.addWidget(self.scr_minus, 1, 10, 1, 1)
        self.scr_n_1 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_1.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_1.setAutoFillBackground(True)
        self.scr_n_1.setScaledContents(False)
        self.scr_n_1.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_1.setObjectName("scr_n_1")
        self.qwe_2.addWidget(self.scr_n_1, 1, 0, 1, 1)
        self.scr_n_2 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_2.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_2.setAutoFillBackground(True)
        self.scr_n_2.setScaledContents(False)
        self.scr_n_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_2.setObjectName("scr_n_2")
        self.qwe_2.addWidget(self.scr_n_2, 1, 1, 1, 1)
        self.scr_n_3 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_3.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_3.setAutoFillBackground(True)
        self.scr_n_3.setScaledContents(False)
        self.scr_n_3.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_3.setObjectName("scr_n_3")
        self.qwe_2.addWidget(self.scr_n_3, 1, 2, 1, 1)
        self.scr_n_4 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_4.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_4.setAutoFillBackground(True)
        self.scr_n_4.setScaledContents(False)
        self.scr_n_4.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_4.setObjectName("scr_n_4")
        self.qwe_2.addWidget(self.scr_n_4, 1, 3, 1, 1)
        self.scr_n_5 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_5.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_5.setAutoFillBackground(True)
        self.scr_n_5.setScaledContents(False)
        self.scr_n_5.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_5.setObjectName("scr_n_5")
        self.qwe_2.addWidget(self.scr_n_5, 1, 4, 1, 1)
        self.scr_n_6 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_6.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_6.setAutoFillBackground(True)
        self.scr_n_6.setScaledContents(False)
        self.scr_n_6.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_6.setObjectName("scr_n_6")
        self.qwe_2.addWidget(self.scr_n_6, 1, 5, 1, 1)
        self.scr_n_7 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_7.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_7.setAutoFillBackground(True)
        self.scr_n_7.setScaledContents(False)
        self.scr_n_7.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_7.setObjectName("scr_n_7")
        self.qwe_2.addWidget(self.scr_n_7, 1, 6, 1, 1)
        self.scr_n_8 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_8.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_8.setAutoFillBackground(True)
        self.scr_n_8.setScaledContents(False)
        self.scr_n_8.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_8.setObjectName("scr_n_8")
        self.qwe_2.addWidget(self.scr_n_8, 1, 7, 1, 1)
        self.scr_n_9 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_9.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_9.setAutoFillBackground(True)
        self.scr_n_9.setScaledContents(False)
        self.scr_n_9.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_9.setObjectName("scr_n_9")
        self.qwe_2.addWidget(self.scr_n_9, 1, 8, 1, 1)
        self.scr_n_0 = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.scr_n_0.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_n_0.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_n_0.setAutoFillBackground(True)
        self.scr_n_0.setScaledContents(False)
        self.scr_n_0.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_n_0.setObjectName("scr_n_0")
        self.qwe_2.addWidget(self.scr_n_0, 1, 9, 1, 1)
        self.gridLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 51, 61))
        self.gridLayoutWidget_8.setAutoFillBackground(True)
        self.gridLayoutWidget_8.setObjectName("gridLayoutWidget_8")
        self.Tab_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_8)
        self.Tab_2.setContentsMargins(0, 0, 0, 0)
        self.Tab_2.setObjectName("Tab_2")
        self.btn_tilde = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.btn_tilde.setTabletTracking(False)
        self.btn_tilde.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_tilde.setAutoFillBackground(True)
        self.btn_tilde.setScaledContents(False)
        self.btn_tilde.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_tilde.setWordWrap(False)
        self.btn_tilde.setOpenExternalLinks(False)
        self.btn_tilde.setObjectName("btn_tilde")
        self.Tab_2.addWidget(self.btn_tilde, 0, 0, 1, 1)
        self.scr_tilde = QtWidgets.QLabel(self.gridLayoutWidget_8)
        self.scr_tilde.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_tilde.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_tilde.setAutoFillBackground(True)
        self.scr_tilde.setScaledContents(False)
        self.scr_tilde.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_tilde.setObjectName("scr_tilde")
        self.Tab_2.addWidget(self.scr_tilde, 1, 0, 1, 1)
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 250, 241, 61))
        self.gridLayoutWidget_9.setAutoFillBackground(True)
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.qwe_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.qwe_3.setContentsMargins(0, 0, 0, 0)
        self.qwe_3.setObjectName("qwe_3")
        self.btn_ctrl = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.btn_ctrl.setMinimumSize(QtCore.QSize(54, 0))
        self.btn_ctrl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ctrl.setAutoFillBackground(True)
        self.btn_ctrl.setScaledContents(False)
        self.btn_ctrl.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_ctrl.setObjectName("btn_ctrl")
        self.qwe_3.addWidget(self.btn_ctrl, 0, 0, 1, 1)
        self.btn_win = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.btn_win.setAutoFillBackground(True)
        self.btn_win.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_win.setObjectName("btn_win")
        self.qwe_3.addWidget(self.btn_win, 0, 1, 1, 1)
        self.btn_alt = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.btn_alt.setAutoFillBackground(True)
        self.btn_alt.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_alt.setObjectName("btn_alt")
        self.qwe_3.addWidget(self.btn_alt, 0, 2, 1, 1)
        self.scr_ctrl = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.scr_ctrl.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_ctrl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_ctrl.setAutoFillBackground(True)
        self.scr_ctrl.setScaledContents(False)
        self.scr_ctrl.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_ctrl.setObjectName("scr_ctrl")
        self.qwe_3.addWidget(self.scr_ctrl, 1, 0, 1, 1)
        self.scr_win = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.scr_win.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_win.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_win.setAutoFillBackground(True)
        self.scr_win.setScaledContents(False)
        self.scr_win.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_win.setObjectName("scr_win")
        self.qwe_3.addWidget(self.scr_win, 1, 1, 1, 1)
        self.scr_alt = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.scr_alt.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_alt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_alt.setAutoFillBackground(True)
        self.scr_alt.setScaledContents(False)
        self.scr_alt.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_alt.setObjectName("scr_alt")
        self.qwe_3.addWidget(self.scr_alt, 1, 2, 1, 1)
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(250, 250, 311, 61))
        self.gridLayoutWidget_10.setAutoFillBackground(True)
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.Shift_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.Shift_2.setContentsMargins(0, 0, 0, 0)
        self.Shift_2.setObjectName("Shift_2")
        self.btn_space = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.btn_space.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_space.setAutoFillBackground(True)
        self.btn_space.setScaledContents(False)
        self.btn_space.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_space.setObjectName("btn_space")
        self.Shift_2.addWidget(self.btn_space, 0, 0, 1, 1)
        self.scr_space = QtWidgets.QLabel(self.gridLayoutWidget_10)
        self.scr_space.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_space.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_space.setAutoFillBackground(True)
        self.scr_space.setScaledContents(False)
        self.scr_space.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_space.setObjectName("scr_space")
        self.Shift_2.addWidget(self.scr_space, 1, 0, 1, 1)
        self.gridLayoutWidget_11 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_11.setGeometry(QtCore.QRect(560, 250, 171, 61))
        self.gridLayoutWidget_11.setAutoFillBackground(True)
        self.gridLayoutWidget_11.setObjectName("gridLayoutWidget_11")
        self.qwe_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_11)
        self.qwe_4.setContentsMargins(0, 0, 0, 0)
        self.qwe_4.setObjectName("qwe_4")
        self.btn_rctrl = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.btn_rctrl.setAutoFillBackground(True)
        self.btn_rctrl.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_rctrl.setObjectName("btn_rctrl")
        self.qwe_4.addWidget(self.btn_rctrl, 0, 1, 1, 1)
        self.btn_ralt = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.btn_ralt.setMinimumSize(QtCore.QSize(54, 0))
        self.btn_ralt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ralt.setAutoFillBackground(True)
        self.btn_ralt.setScaledContents(False)
        self.btn_ralt.setAlignment(QtCore.Qt.AlignCenter)
        self.btn_ralt.setObjectName("btn_ralt")
        self.qwe_4.addWidget(self.btn_ralt, 0, 0, 1, 1)
        self.scr_ralt = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.scr_ralt.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_ralt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_ralt.setAutoFillBackground(True)
        self.scr_ralt.setScaledContents(False)
        self.scr_ralt.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_ralt.setObjectName("scr_ralt")
        self.qwe_4.addWidget(self.scr_ralt, 1, 0, 1, 1)
        self.scr_rctrl = QtWidgets.QLabel(self.gridLayoutWidget_11)
        self.scr_rctrl.setMaximumSize(QtCore.QSize(16777215, 13))
        self.scr_rctrl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scr_rctrl.setAutoFillBackground(True)
        self.scr_rctrl.setScaledContents(False)
        self.scr_rctrl.setAlignment(QtCore.Qt.AlignCenter)
        self.scr_rctrl.setObjectName("scr_rctrl")
        self.qwe_4.addWidget(self.scr_rctrl, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.keys_name()
        self.keyboard_activate()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_w.setText(_translate("MainWindow", "W"))
        self.btn_u.setText(_translate("MainWindow", "U"))
        self.btn_q.setText(_translate("MainWindow", "Q"))
        self.btn_o.setText(_translate("MainWindow", "O"))
        self.btn_op_scq_br.setText(_translate("MainWindow", "["))
        self.btn_p.setText(_translate("MainWindow", "P"))
        self.btn_i.setText(_translate("MainWindow", "I"))
        self.btn_y.setText(_translate("MainWindow", "Y"))
        self.btn_t.setText(_translate("MainWindow", "T"))
        self.scr_p.setText(_translate("MainWindow", "0"))
        self.scr_i.setText(_translate("MainWindow", "0"))
        self.btn_cl_sqr_br.setText(_translate("MainWindow", "]"))
        self.scr_op_scq_b.setText(_translate("MainWindow", "0"))
        self.scr_w.setText(_translate("MainWindow", "0"))
        self.scr_cl_sqr_br.setText(_translate("MainWindow", "0"))
        self.scr_t.setText(_translate("MainWindow", "0"))
        self.scr_y.setText(_translate("MainWindow", "0"))
        self.scr_u.setText(_translate("MainWindow", "0"))
        self.scr_o.setText(_translate("MainWindow", "0"))
        self.scr_e.setText(_translate("MainWindow", "0"))
        self.scr_r.setText(_translate("MainWindow", "0"))
        self.btn_r.setText(_translate("MainWindow", "R"))
        self.btn_e.setText(_translate("MainWindow", "E"))
        self.scr_q.setText(_translate("MainWindow", "0"))
        self.btn_g.setText(_translate("MainWindow", "G"))
        self.btn_d.setText(_translate("MainWindow", "D"))
        self.btn_f.setText(_translate("MainWindow", "F"))
        self.scr_a.setText(_translate("MainWindow", "0"))
        self.btn_a.setText(_translate("MainWindow", "A"))
        self.btn_semicolon.setText(_translate("MainWindow", ";"))
        self.btn_k.setText(_translate("MainWindow", "K"))
        self.btn_h.setText(_translate("MainWindow", "H"))
        self.btn_s.setText(_translate("MainWindow", "S"))
        self.btn_j.setText(_translate("MainWindow", "J"))
        self.btn_l.setText(_translate("MainWindow", "L"))
        self.btn_apstf.setText(_translate("MainWindow", "\'"))
        self.scr_s.setText(_translate("MainWindow", "0"))
        self.scr_d.setText(_translate("MainWindow", "0"))
        self.scr_f.setText(_translate("MainWindow", "0"))
        self.scr_g.setText(_translate("MainWindow", "0"))
        self.scr_h.setText(_translate("MainWindow", "0"))
        self.scr_j.setText(_translate("MainWindow", "0"))
        self.scr_k.setText(_translate("MainWindow", "0"))
        self.scr_l.setText(_translate("MainWindow", "0"))
        self.scr_semicolon.setText(_translate("MainWindow", "0"))
        self.scr_apstrf.setText(_translate("MainWindow", "0"))
        self.btn_z.setText(_translate("MainWindow", "Z"))
        self.btn_m.setText(_translate("MainWindow", "M"))
        self.btn_dot.setText(_translate("MainWindow", "."))
        self.btn_b.setText(_translate("MainWindow", "B"))
        self.btn_c.setText(_translate("MainWindow", "C"))
        self.btn_comma.setText(_translate("MainWindow", ","))
        self.btn_f_slash.setText(_translate("MainWindow", "/"))
        self.btn_n.setText(_translate("MainWindow", "N"))
        self.btn_v.setText(_translate("MainWindow", "V"))
        self.btn_x.setText(_translate("MainWindow", "X"))
        self.scr_z.setText(_translate("MainWindow", "0"))
        self.scr_x.setText(_translate("MainWindow", "0"))
        self.scr_c.setText(_translate("MainWindow", "0"))
        self.scr_v.setText(_translate("MainWindow", "0"))
        self.scr_b.setText(_translate("MainWindow", "0"))
        self.scr_n.setText(_translate("MainWindow", "0"))
        self.scr_m.setText(_translate("MainWindow", "0"))
        self.scr_comma.setText(_translate("MainWindow", "0"))
        self.scr_dot.setText(_translate("MainWindow", "0"))
        self.scr_f_slash.setText(_translate("MainWindow", "0"))
        self.btn_tab.setText(_translate("MainWindow", "Tab"))
        self.scr_tab.setText(_translate("MainWindow", "0"))
        self.btn_capslock.setText(_translate("MainWindow", "Caps Lock"))
        self.scr_capslock.setText(_translate("MainWindow", "0"))
        self.btn_shift.setText(_translate("MainWindow", "Shift"))
        self.scr_shift.setText(_translate("MainWindow", "0"))
        self.btn_minus.setText(_translate("MainWindow", "-"))
        self.btn_9.setText(_translate("MainWindow", "9"))
        self.btn_0.setText(_translate("MainWindow", "0"))
        self.btn_8.setText(_translate("MainWindow", "8"))
        self.btn_equal.setText(_translate("MainWindow", "="))
        self.btn_6.setText(_translate("MainWindow", "6"))
        self.btn_5.setText(_translate("MainWindow", "5"))
        self.btn_4.setText(_translate("MainWindow", "4"))
        self.btn_3.setText(_translate("MainWindow", "3"))
        self.btn_2.setText(_translate("MainWindow", "2"))
        self.btn_1.setText(_translate("MainWindow", "1"))
        self.btn_7.setText(_translate("MainWindow", "7"))
        self.scr_ecuals.setText(_translate("MainWindow", "0"))
        self.scr_minus.setText(_translate("MainWindow", "0"))
        self.scr_n_1.setText(_translate("MainWindow", "0"))
        self.scr_n_2.setText(_translate("MainWindow", "0"))
        self.scr_n_3.setText(_translate("MainWindow", "0"))
        self.scr_n_4.setText(_translate("MainWindow", "0"))
        self.scr_n_5.setText(_translate("MainWindow", "0"))
        self.scr_n_6.setText(_translate("MainWindow", "0"))
        self.scr_n_7.setText(_translate("MainWindow", "0"))
        self.scr_n_8.setText(_translate("MainWindow", "0"))
        self.scr_n_9.setText(_translate("MainWindow", "0"))
        self.scr_n_0.setText(_translate("MainWindow", "0"))
        self.btn_tilde.setText(_translate("MainWindow", "~"))
        self.scr_tilde.setText(_translate("MainWindow", "0"))
        self.btn_ctrl.setText(_translate("MainWindow", "Ctrl"))
        self.btn_win.setText(_translate("MainWindow", "Win"))
        self.btn_alt.setText(_translate("MainWindow", "Alt"))
        self.scr_ctrl.setText(_translate("MainWindow", "0"))
        self.scr_win.setText(_translate("MainWindow", "0"))
        self.scr_alt.setText(_translate("MainWindow", "0"))
        self.btn_space.setText(_translate("MainWindow", "Space"))
        self.scr_space.setText(_translate("MainWindow", "0"))
        self.btn_rctrl.setText(_translate("MainWindow", "rCtrl"))
        self.btn_ralt.setText(_translate("MainWindow", "rAlt"))
        self.scr_ralt.setText(_translate("MainWindow", "0"))
        self.scr_rctrl.setText(_translate("MainWindow", "0"))


    def keyboard_activate(self):
        keyboard.hook(self.print_pressed_keys)


    # при нажатии клавиши прибавляем единицу к счету нажатия
    def click_up(self, btn, smvls_dict):
        if btn in smvls_dict:
            smvls_dict[btn] += 1
            self.scr_name[btn].setText(str(smvls_dict[btn]))

    
    # меняем фон клавиш при их нажатии
    def background(self, type, name):
        btn_name = self.btn_name[name]

        if type == 'on':
            btn_name.setStyleSheet("background-color: rgb(186, 186, 186);")
        if type == 'off':
            btn_name.setStyleSheet("background-color: rgb(240, 240, 240);")


    def ru2en(self, btn):
        simvols_ru = ['ё','й','ц','у','к','е','н','г','ш','щ','з','х','ъ',
                      'ф','ы','в','а','п','р','о','л','д','ж','э',
                      'я','ч','с','м','и','т','ь','б','ю', '.']

        simvols_en = ['`','q','w','e','r','t','y','u','i','o','p','[',']',
                      'a','s','d','f','g','h','j','k','l',';',"'",
                      'z','x','c','v','b','n','m',',','.', '/']

        # пеоеводим символы русской клавиатуры в символы английской
        if btn in simvols_ru:
            btn = simvols_en[simvols_ru.index(btn)]

        return btn


    def print_pressed_keys(self, e):
        if e.event_type == 'down':
        	# превращаем в строку
        	# переводим в нижний регистр
            # меняем русскую раскладку на английскую
            btn = self.ru2en((str(e.name)).lower())
            self.background('on', btn)

        if e.event_type == 'up':
            btn = self.ru2en((str(e.name)).lower())
            self.background('off', btn)

            smvls_dict = self.smvls_dict

            if btn in smvls_dict:
                print('btn', btn)
                print('e.name', e.name)
                self.click_up(btn, smvls_dict)


    # функция содержит в себе словари
    # 1. счета нажатых клавиш (letters_dict, smvls_dict)
    # 2. имена переменных соответствующие нажатым клавишам получаемых с e.name (btn_name, scr_nameм)
    def keys_name(self):
        # словарь счета нажатых букв
        self.letters_dict = {'q': 0, 'w': 0, 'e': 0, 'r': 0, 't': 0, 'y': 0, 'u': 0, 'i': 0, 'o': 0, 'p': 0,
                             'a': 0, 's': 0, 'd': 0, 'f': 0, 'g': 0, 'h': 0, 'j': 0, 'k': 0, 'l': 0,
                             'z': 0, 'x': 0, 'c': 0, 'v': 0, 'b': 0, 'n': 0, 'm': 0}

        # словарь счета нажатых символов и спец клавиш
        self.smvls_dict = {'q': 0, 'w': 0, 'e': 0, 'r': 0, 't': 0, 'y': 0, 'u': 0, 'i': 0, 'o': 0, 'p': 0,
                           'a': 0, 's': 0, 'd': 0, 'f': 0, 'g': 0, 'h': 0, 'j': 0, 'k': 0, 'l': 0,
                           'z': 0, 'x': 0, 'c': 0, 'v': 0, 'b': 0, 'n': 0, 'm': 0,
                           '+': 0, '*': 0, '-': 0, '-': 0, '=': 0,
                           '`': 0, '1': 0, '2': 0, '3': 0, '4': 0, '5': 0, '6': 0, '7': 0, '8': 0, '9': 0, '0': 0,
                           ',': 0, '.': 0, '/': 0, ';': 0, "'": 0, '[': 0, ']': 0, 
                           'tab': 0, 'caps lock': 0, 'shift': 0, 'ctrl': 0, 'alt': 0, 'space': 0, 'enter': 0,
                           'right alt': 0, 'right ctrl': 0, 'right shift': 0, 'left windows': 0,
                           'right': 0, 'left': 0, 'up': 0, 'down': 0,
                           'num lock': 0, 'insert': 0, 'end': 0, 'home': 0, 'page down': 0, 'page up': 0, 'clear': 0}

        # имена переменных букв (клавиш на клавиатуре)
        self.btn_name = {'q': self.btn_q, 'w': self.btn_w, 'e': self.btn_e, 'r': self.btn_r, 't': self.btn_t, 
                         'y': self.btn_y, 'u': self.btn_u, 'i': self.btn_i, 'o': self.btn_o, 'p': self.btn_p, 
                         'a': self.btn_a, 's': self.btn_s, 'd': self.btn_d, 'f': self.btn_f, 'g': self.btn_g, 
                         'h': self.btn_h, 'j': self.btn_j, 'k': self.btn_k, 'l': self.btn_l, 
                         'z': self.btn_z, 'x': self.btn_x, 'c': self.btn_c, 'v': self.btn_v, 'b': self.btn_b, 
                         'n': self.btn_n, 'm': self.btn_m,

                         '[':self.btn_op_scq_br, ']': self.btn_cl_sqr_br, ';': self.btn_semicolon, 
                         "'":self.btn_apstf, ',': self.btn_comma, '.': self.btn_dot, '/': self.btn_f_slash, 

                         '`': self.btn_tilde, '-': self.btn_minus, '=': self.btn_equal,
                         '1': self.btn_1, '2': self.btn_2, '3': self.btn_3, '4': self.btn_4, '5': self.btn_5, 
                         '6': self.btn_6, '7': self.btn_7, '8': self.btn_8, '9': self.btn_9, '0': self.btn_0,

                         'tab': self.btn_tab, 'caps lock': self.btn_capslock, 'shift': self.btn_shift, 
                         'ctrl': self.btn_ctrl, 'alt': self.btn_alt, 'space': self.btn_space,
                         'left windows': self.btn_win, 'right alt': self.btn_ralt, 'right ctrl': self.btn_rctrl}

        # имена переменных счета (циферки под бувами)
        self.scr_name = {'q': self.scr_q, 'w': self.scr_w, 'e': self.scr_e, 'r': self.scr_r, 't': self.scr_t,
                         'y': self.scr_y, 'u': self.scr_u, 'i': self.scr_i, 'o': self.scr_o, 'p': self.scr_p,
                         'a': self.scr_a, 's': self.scr_s, 'd': self.scr_d, 'f': self.scr_f, 'g': self.scr_g,
                         'h': self.scr_h, 'j': self.scr_j, 'k': self.scr_k, 'l': self.scr_l,
                         'z': self.scr_z, 'x': self.scr_x, 'c': self.scr_c, 'v': self.scr_v, 'b': self.scr_b,
                         'n': self.scr_n, 'm': self.scr_m,

                         '[': self.scr_op_scq_b, ']': self.scr_cl_sqr_br, ';': self.scr_semicolon,
                         "'": self.scr_apstrf, ',': self.scr_comma, '.': self.scr_dot, '/': self.scr_f_slash,

                         '`': self.scr_tilde, '-': self.scr_minus, '=': self.scr_ecuals,
                         '1': self.scr_n_1, '2': self.scr_n_2, '3': self.scr_n_3, '4': self.scr_n_4, '5': self.scr_n_5,
                         '6': self.scr_n_6, '7': self.scr_n_7, '8': self.scr_n_8, '9': self.scr_n_9, '0': self.scr_n_0,

                         'tab': self.scr_tab, 'caps lock': self.scr_capslock, 'shift': self.scr_shift,
                         'ctrl': self.scr_ctrl, 'alt': self.scr_alt, 'space': self.scr_space,
                         'left windows': self.scr_win, 'right alt': self.scr_ralt, 'right ctrl': self.scr_rctrl}


if __name__ == "__main__":
    import sys
    import keyboard
    import asyncio

    btn_clicks = {}
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
